-- MySQL Script generated by MySQL Workbench
-- Thu Sep  3 17:39:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pcparts_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pcparts_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pcparts_db` DEFAULT CHARACTER SET utf8 ;
USE `pcparts_db` ;

-- -----------------------------------------------------
-- Table `pcparts_db`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcparts_db`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcparts_db`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcparts_db`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `country_country_id` INT NOT NULL,
  PRIMARY KEY (`city_id`, `country_country_id`),
  INDEX `fk_city_country1_idx` (`country_country_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_country_id`)
    REFERENCES `pcparts_db`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcparts_db`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcparts_db`.`adress` (
  `adress_id` INT NOT NULL AUTO_INCREMENT,
  `adress_street_name` VARCHAR(45) NOT NULL,
  `adress_street_number` VARCHAR(45) NOT NULL,
  `city_city_id` INT NOT NULL,
  PRIMARY KEY (`adress_id`, `city_city_id`),
  INDEX `fk_adress_city1_idx` (`city_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_adress_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `pcparts_db`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcparts_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcparts_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_phonenumber` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `adress_adress_id` INT NOT NULL,
  `adress_city_city_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `adress_adress_id`, `adress_city_city_id`),
  UNIQUE INDEX `iduser_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  INDEX `fk_user_adress1_idx` (`adress_adress_id` ASC, `adress_city_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_adress1`
    FOREIGN KEY (`adress_adress_id` , `adress_city_city_id`)
    REFERENCES `pcparts_db`.`adress` (`adress_id` , `city_city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcparts_db`.`pc_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcparts_db`.`pc_parts` (
  `part_id` INT NOT NULL AUTO_INCREMENT,
  `part_name` TEXT(80) NOT NULL,
  `part_price` FLOAT NOT NULL,
  `part_stock` INT NULL,
  `part_manufacturer` TEXT(80) NULL,
  `part_warranty` INT NULL,
  `part_info` LONGTEXT NULL,
  `part_image` VARCHAR(45) NULL,
  PRIMARY KEY (`part_id`),
  UNIQUE INDEX `part_id_UNIQUE` (`part_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcparts_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcparts_db`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_price` FLOAT NOT NULL,
  `order_date` DATE NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  `user_user_id` INT NOT NULL,
  `adress_adress_id` INT NOT NULL,
  `adress_city_city_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `user_user_id`, `adress_adress_id`, `adress_city_city_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_user_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_order_adress1_idx` (`adress_adress_id` ASC, `adress_city_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `pcparts_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_adress1`
    FOREIGN KEY (`adress_adress_id` , `adress_city_city_id`)
    REFERENCES `pcparts_db`.`adress` (`adress_id` , `city_city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcparts_db`.`orders_has_pc_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcparts_db`.`orders_has_pc_parts` (
  `orders_order_id` INT NOT NULL,
  `orders_user_user_id` INT NOT NULL,
  `orders_adress_adress_id` INT NOT NULL,
  `orders_adress_city_city_id` INT NOT NULL,
  `pc_parts_part_id` INT NOT NULL,
  PRIMARY KEY (`orders_order_id`, `orders_user_user_id`, `orders_adress_adress_id`, `orders_adress_city_city_id`, `pc_parts_part_id`),
  INDEX `fk_order_has_pc_parts_pc_parts1_idx` (`pc_parts_part_id` ASC) VISIBLE,
  INDEX `fk_order_has_pc_parts_order1_idx` (`orders_order_id` ASC, `orders_user_user_id` ASC, `orders_adress_adress_id` ASC, `orders_adress_city_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_pc_parts_order1`
    FOREIGN KEY (`orders_order_id` , `orders_user_user_id` , `orders_adress_adress_id` , `orders_adress_city_city_id`)
    REFERENCES `pcparts_db`.`orders` (`order_id` , `user_user_id` , `adress_adress_id` , `adress_city_city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_pc_parts_pc_parts1`
    FOREIGN KEY (`pc_parts_part_id`)
    REFERENCES `pcparts_db`.`pc_parts` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pcparts_db`.`country`
-- -----------------------------------------------------
START TRANSACTION;
USE `pcparts_db`;
INSERT INTO `pcparts_db`.`country` (`country_id`, `country_name`) VALUES (1, 'Admin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pcparts_db`.`city`
-- -----------------------------------------------------
START TRANSACTION;
USE `pcparts_db`;
INSERT INTO `pcparts_db`.`city` (`city_id`, `city_name`, `country_country_id`) VALUES (1, 'admin', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pcparts_db`.`adress`
-- -----------------------------------------------------
START TRANSACTION;
USE `pcparts_db`;
INSERT INTO `pcparts_db`.`adress` (`adress_id`, `adress_street_name`, `adress_street_number`, `city_city_id`) VALUES (1, 'admin', 'admin', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pcparts_db`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `pcparts_db`;
INSERT INTO `pcparts_db`.`user` (`user_id`, `user_name`, `user_email`, `user_phonenumber`, `user_password`, `user_admin`, `adress_adress_id`, `adress_city_city_id`) VALUES (1, 'Admin', 'Admin@gmail.com', 'Admin', 'Admin', 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pcparts_db`.`pc_parts`
-- -----------------------------------------------------
START TRANSACTION;
USE `pcparts_db`;
INSERT INTO `pcparts_db`.`pc_parts` (`part_id`, `part_name`, `part_price`, `part_stock`, `part_manufacturer`, `part_warranty`, `part_info`, `part_image`) VALUES (1, 'Nvidia GTX 2060', 400, 4, 'Nvidia', 3, 'Vram: 6GB, Core Clock: 1350mhz', 'gpu1.png');
INSERT INTO `pcparts_db`.`pc_parts` (`part_id`, `part_name`, `part_price`, `part_stock`, `part_manufacturer`, `part_warranty`, `part_info`, `part_image`) VALUES (2, 'Kingston 8GB 3666Mhz Ram', 80, 20, 'Kingston', 2, 'Ram: 8GB, Ram Clock: 3666Mhz', 'ram1.png');
INSERT INTO `pcparts_db`.`pc_parts` (`part_id`, `part_name`, `part_price`, `part_stock`, `part_manufacturer`, `part_warranty`, `part_info`, `part_image`) VALUES (3, 'Intel i7 8600k', 380, 6, 'Intel', 3, 'Base Clock: 3.2Ghz, Turbo Clock: 4.5Ghz, Cores: 8, Threads: 16, Cache: 16MB', 'cpu1.png');

COMMIT;

